### ISSUE TITLE
scrollView is not defined in atom 1.16beta

### ISSUE THREAD

**Issue by netizen-ais** [mupchrch/outline-selection#11]
[Enter steps to reproduce:]

1. Open or restart atom

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Ubuntu Zesty
**Thrown From**: [outline-selection](https://github.com/mupchrch/outline-selection) package 0.3.1

### Stack Trace

```
At scrollView is not defined

ReferenceError: scrollView is not defined
    at OutlineSelectionView.attach (outline-selection-view.js:52:22)
    at outline-selection.js:24:27
    at TextEditor.module.exports.TextEditor.observeSelections (/app.asar/src/text-editor.js:678:9)
    at outline-selection.js:21:14
    at Workspace.observeTextEditors (/app.asar/src/workspace.js:305:53)
    at Object.activate (outline-selection.js:18:20)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

**Comment by mupchrch** [comment]
Sorry for such a late reply, is this still reproducible?
