### ISSUE TITLE
Failed to activate the outline-selection package

### ISSUE THREAD

**Issue by paul-piro** [mupchrch/outline-selection#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [outline-selection](https://github.com/mupchrch/outline-selection) package 0.3.1

### Stack Trace

Failed to activate the outline-selection package

```
At Cannot read property 'NaN' of undefined

TypeError: Cannot read property 'NaN' of undefined
    at TextEditorComponent.renderedScreenLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:918:37)
    at TextEditorComponent.pixelLeftForRowAndColumn (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2254:35)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:199:46)
    at HTMLElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:243:32)
    at HTMLElement.pixelRectForScreenRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:253:24)
    at _updateOutline (/packages/outline-selection/lib/outline-selection.js:113:32)
    at /packages/outline-selection/lib/outline-selection.js:25:9
    at TextEditor.module.exports.TextEditor.observeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:762:15)
    at /packages/outline-selection/lib/outline-selection.js:21:14
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/packages/outline-selection/lib/outline-selection.js:18:20)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.4 
autoclose-html 0.23.0 
base16-ocean-dark-spacegray 0.13.0 
base16-ocean-dark-syntax-theme 0.1.10 
busy-signal 1.4.3 
duotone-dark-syntax 2.1.0 
file-watcher 1.1.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.69.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
material-syntax 0.6.1 
minimap 4.29.3 
oceanic-next 1.0.0 
one-dark-vivid-syntax 1.8.0 
outline-selection 0.3.1 
pigments 0.40.1 
tomorrow-night-eighties-syntax 1.0.2 
```

**Comment by paul-piro** [comment]
This extension doesn't work anymore with the latest Atom 1.19.0 it acting very weird, when the user doesn't get this error the selelction it's just a rectangle

**Comment by jolsen71** [comment]
I'm seeing strange highlighting issues with 1.19.0 as well. I've included a visual where you can see the outline color (bright white) differences from the actual selection (the light gray background). 

![examplehighlight](https://user-images.githubusercontent.com/6641548/29176579-d7d5feae-7db1-11e7-9167-504f87952156.gif)

**Comment by paul-piro** [comment]
Yes, that's the problem.
Is this package still alive?

**Comment by irvnriir** [comment]
same problem

**Comment by mupchrch** [comment]
> Is this package still alive?

Still alive but it's barely breathing 😜 

In all seriousness, I am hoping to find time this weekend to look into the issue - sorry for the delay.

**Comment by jolsen71** [comment]
@mupchrch we appreciate this project and everything you done and do. Thank you!

**Comment by paul-piro** [comment]
@mupchrch Thank you for this extension, it makes Atom prettier :)

**Comment by mupchrch** [comment]
Thanks for the kind words!

I have logged https://github.com/atom/atom/issues/15284 for this. The most important API for `outline-selection` seems to have been broken by the text editor rendering rewrite in the latest version.

**Comment by paul-piro** [comment]
Any hope that they will provide the API call?

**Comment by mupchrch** [comment]
@paul321 I feel like this would be the only package that would need that API call, so I'm not sure they'd expose it. I might still request either they expose it or they somehow implement the functionality of this package into core themselves.

For now, I am putting in an attempted fix, so that the package will hopefully work in the interim.

**Comment by mupchrch** [comment]
Still happening randomly because this package is still relying on `pixelPositionForScreenPosition`. Will need to either rethink implementation or request the API.

**Comment by irvnriir** [comment]
:_(

**Comment by irvnriir** [comment]
[highlight-selected package](https://github.com/richrace/highlight-selected) have same visual functionality and do not have the issue

[img]https://img-fotki.yandex.ru/get/1012238/111360945.2/0_1bc99c_d5e4ca24_orig [/img]

, think solution can be found in it

**Comment by mupchrch** [comment]
The issue is that I wanted this package to be able to outline the selection as a whole even if it wraps onto multiple lines, which makes it a bit harder than what `highlight-selected` package is doing.

Here is an example - I've turned on softwrap to show what I mean about outlining the selection as a whole:

![image](https://user-images.githubusercontent.com/5797698/38696211-85eced5c-3e5c-11e8-9346-890b06831f8e.png)

Notice `highlight-selected` outlines each line individually.

**Comment by irvnriir** [comment]
@mupchrch well, yeah, got it, my mis, really its better, i bit suprised that `outline` do working some times and randomly do not, from outside looks like it mean that the issue not hardcored

**Comment by irvnriir** [comment]
Noticed that the issue happens when some selection in some file|s left on editor close.
Could function to remove all selections on editor load ,If its possible .be a solution?

**Comment by Diks3n** [comment]
The problem remains - if at startup the selection was in SEVERAL files then - the plugin knocks out an error and don't work
win7 x64
atom 1.53.0 x64
