### ISSUE TITLE
Outline doesn't show up for multiple selections (also, error)

### ISSUE THREAD

**Issue by calebmeyer** [mupchrch/outline-selection#7]
![screen shot 2016-06-16 at 9 55 53 am](https://cloud.githubusercontent.com/assets/3342777/16121372/9d796466-33a8-11e6-9956-475724789bcf.png)

Steps to reproduce the errror:
1. Select multiple things using Cmd-d
2. Once you've selected all the available items, hit Cmd-d again

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5 (El Capitan)
**Thrown From**: [outline-selection](https://github.com/mupchrch/outline-selection) package, v0.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At /Users/cm022291/.atom/packages/outline-selection/lib/outline-selection.js:47

TypeError: Cannot read property 'destroy' of undefined
    at /Users/cm022291/.atom/packages/outline-selection/lib/outline-selection.js:47:26
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.removeSelection (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2283:27)
    at Selection.module.exports.Selection.markerDidDestroy (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/selection.js:945:19)
    at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/selection.js:46:24
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditorMarker.module.exports.TextEditorMarker.destroyed (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:229:20)
    at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:37:24
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Marker.module.exports.Marker.destroy (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:252:27)
    at TextEditorMarker.module.exports.TextEditorMarker.destroy (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:43:25)
    at Selection.module.exports.Selection.destroy (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/selection.js:52:26)
    at Selection.module.exports.Selection.merge (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/selection.js:893:29)
    at reducer (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2231:29)
    at Array.reduce (native)
    at Object._.reduce._.foldl._.inject (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:114:28)
    at TextEditor.module.exports.TextEditor.mergeSelections (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2238:9)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2186:35)
    at TextEditor.module.exports.TextEditor.addSelection (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2261:12)
    at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:109:18
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:388:22)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:193:19)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1933:34)
    at SelectNext.module.exports.SelectNext.addSelection (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/select-next.js:125:31)
    at SelectNext.module.exports.SelectNext.selectNextOccurrence (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/select-next.js:107:21)
    at SelectNext.module.exports.SelectNext.findAndSelectNext (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/select-next.js:20:21)
    at atom-text-editor.atom.commands.add.find-and-replace:select-next (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find.js:168:57)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -4:10.9.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 48x -3:58.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:56 dotfiles:open-stylesheet (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:42.5.0 editor:toggle-line-comments (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -2:40 core:save (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -2:31.1.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:25.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:41.9.0 core:backspace (atom-text-editor#outline-selection.outlineWidth.editor.mini.is-focused)
 18x -1:18 find-and-replace:select-next (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "language-mustache",
      "linter-haml",
      "deprecation-cop",
      "overrides",
      "autocomplete-paths",
      "linter-foodcritic",
      "linter-less",
      "line-ending-selector",
      "org",
      "terminal-plus",
      "glowing-cursor",
      "pigments",
      "minimap-autohide",
      "linter-rubocop",
      "linter",
      "linter-proselint",
      "minimap-cursorline"
    ],
    "packagesWithKeymapsDisabled": [
      "ruby-test-switcher"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "outline-selection": {
    "outlineColor": {
      "red": 61,
      "green": 190,
      "blue": 255,
      "alpha": 1
    },
    "outlineOpacity": 0.75,
    "outlineWidth": 2
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, v0.29.8
atom-jasmine, v0.8.1
auto-update-packages, v1.0.1
file-icons, v1.7.14
highlight-line, v0.11.1
language-diff, v0.4.0
language-gitignore, v0.2.0
language-haml, v0.24.0
language-lisp, v0.2.0
language-log, v1.4.0
language-restructuredtext, v0.16.0
language-rspec, v0.5.0
language-rust, v0.4.6
linter-eslint, v7.2.2
merge-conflicts, v1.4.4
minimap, v4.24.6
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
monokai, v0.18.0
omni-ruler, v0.4.2
open-recent, v5.0.0
outline-selection, v0.2.2
pain-split, v1.4.0
racer, v0.20.0
react, v0.15.0
ruby-test-switcher, v1.2.1
set-syntax, v0.3.0
symbol-gen, v1.3.1
trailing-spaces, v0.3.2
vim-mode, v0.65.1

# Dev
fuzzy-finder, v1.2.0
```

**Comment by mupchrch** [comment]
I am not getting the error you got, but the rest of the selections aren't highlighting like you noticed. I'll keep investigating - thanks for the report!
